apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: guestbook-ui-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  rules:
  - host: guestbook-default.192.168.39.233.nip.io
    http:
      paths:
      - backend:
          serviceName: guestbook-ui
          servicePort: https
